select * from us_regional_sales_data;

# adding revenue generated column

alter table us_regional_sales_data add
column `revenue generated` double;

update us_regional_sales_data
 set `revenue generated`=`unit price`*`order quantity`*`discount applied`;

# adding profit column

alter table us_regional_sales_data add
column profit double;

update us_regional_sales_data
 set profit=(`unit price`-`unit cost`)*`order quantity`*`discount applied`;

# revenue generated by sales channel
select `Sales Channel`,sum(`revenue generated`) from us_regional_sales_data
group by `Sales Channel`;

# most discount offered by which channel
with ca as
(
select `sales channel`,count(*) cc
from us_regional_sales_data
where `Discount Applied`=(select max(`Discount Applied`) from us_regional_sales_data)
group by `Sales Channel`
)
select * from ca where cc=(select max(cc) from ca);

# average time span between deliverys of channels
with a1 as(
select `Sales Channel`,(day(deliveryDate)+month(deliveryDate)*30)-
((day(orderdate)+month(orderdate)*30)) deliverygap from us_regional_sales_data

)select a1.`sales channel`,avg(deliverygap) from a1
join us_regional_sales_data
on a1.`sales channel`=us_regional_sales_data.`Sales Channel`
group by a1.`sales channel`;

# most profitable channel
select `sales channel`,sum(profit) from us_regional_sales_data
group by `sales channel`;
